### PR TITLE
Refactor header, fix cookies issue, you know where to find me

### PR DESCRIPTION
**Pull request by ysabri**

### CODE REVIEW

**Review by kreloff-01 — COMMENTED** [review]
has this been tested by going through the sign up with  no failures

**Comment by kreloff-01** [comment]
I'm susing these  cookie changes. I've been burned before

**Comment by ysabri** [comment]
> I'm susing these  cookie changes. I've been burned before

Only way to find out

**Review by kreloff-01 — CHANGES_REQUESTED** [review]
no touch cookies pl0x

**Comment by ysabri** [comment]
@kreloff-01 I fixed the shit

**Pull request merged**
