### PR TITLE
Make footer smaller

### PR DESCRIPTION
**Pull request by ysabri**
It works for the homepage.

There is an issue in signup page, the root div doesn't expand to the
bottom of the page.

I don't know if this is the case in other pages.

I know it is not an issue with the footer since it is at the very bottom
of the root div.

ie. the root div not reaching bottom of page is a different issue.

### CODE REVIEW

**Comment by kalshafei** [comment]
Will mixing and matching using exact pixel sizing vs percentages for some of the sizing's lead to issues if we mess with parents?

**Comment by ysabri** [comment]
> Will mixing and matching using exact pixel sizing vs percentages for some of the sizing's lead to issues if we mess with parents? 

That's a fair point, I thought of it too. I only used it within the footer div to decide on the image size. I wanted to fix it so when it moves the image doesn't get messed up or moved. There is probably a better way to do the whole thing in bootstrap, especially the grid itself. This works for now....unless we want the app to be responsive.

**Review by kalshafei — APPROVED** [review]
looks good enough to me

**Pull request merged**
